[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
eclipse.project.name = appName + '-core'

dependencies {
  api "com.badlogicgames.gdx:gdx:$gdxVersion"
  api "io.github.quillraven.libktx:ktx-app:$ktxVersion"
  api "io.github.quillraven.libktx:ktx-assets:$ktxVersion"
  api "io.github.quillraven.libktx:ktx-collections:$ktxVersion"
  api "io.github.quillraven.libktx:ktx-graphics:$ktxVersion"
  api "io.github.quillraven.libktx:ktx-scene2d:$ktxVersion"
  api "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"

  if(enableGraalNative == 'true') {
    implementation "io.github.berstanio:gdx-svmhelper-annotations:$graalHelperVersion"
  }
}

jar {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
